# xi. Model Inference

In [1]:
#libraries untuk di data inference
import pickle
import pandas as pd
import numpy as np
import random

In [2]:
#load model scaler dan model knn yang sudah disimpen dalam bentuk pkl
with open('scaler.pkl', 'rb') as file_1:
  scaler = pickle.load(file_1)

with open('model_knn.pkl', 'rb') as file_2:
  model_knn = pickle.load(file_2)

## Membuat data dummy

In [3]:
# Atur seed di sini
seed_value = 7771
random.seed(seed_value)
np.random.seed(seed_value)

# Jumlah data point yang ingin dibuat
n = 100

# Membuat data untuk kolom 'limit_balance'
limit_balance = np.round(np.random.uniform(10000, 800000, n), 2)

# Membuat data untuk kolom 'pay_1,pay_2,pay_3,pay_4,pay_5,pay_6'
pay_1 = [-2.0,-1.0,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0]
pay_1 = random.choices(pay_1, k=n)

pay_2 = [-2.0,-1.0,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0]
pay_2 = random.choices(pay_2, k=n)

pay_3 = [-2.0,-1.0,0.0,2.0,3.0,4.0,5.0,6.0,7.0]
pay_3 = random.choices(pay_3, k=n)

pay_4 = [-2.0,-1.0,0.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0]
pay_4 = random.choices(pay_4, k=n)

pay_5 = [-2.0,-1.0,0.0,2.0,3.0,4.0,5.0,6.0,7.0]
pay_5 = random.choices(pay_5, k=n)

pay_6 = [-2.0,-1.0,0.0,2.0,3.0,4.0,6.0,7.0]
pay_6 = random.choices(pay_6, k=n)

# Membuat DataFrame
df_inf = pd.DataFrame({
    'limit_balance': limit_balance,
    'pay_1': pay_1,
    'pay_2': pay_2,
    'pay_3': pay_3,
    'pay_4': pay_4,
    'pay_5': pay_5,
    'pay_6': pay_6,
    
})

In [4]:
df_inf

    limit_balance  pay_1  pay_2  pay_3  pay_4  pay_5  pay_6
0       589504.01    3.0    7.0   -2.0    5.0    4.0    4.0
1       418154.87    4.0    7.0   -1.0    4.0    5.0    2.0
2       111006.10    7.0    0.0   -1.0    3.0   -1.0   -1.0
3       719503.58   -2.0    5.0    7.0   -2.0   -1.0    7.0
4       644347.27    4.0    6.0    2.0   -1.0    2.0    2.0
..            ...    ...    ...    ...    ...    ...    ...
95      711053.63    2.0    7.0   -2.0    8.0    7.0   -1.0
96       30414.87    5.0    1.0    0.0    3.0   -2.0    4.0
97      765526.27   -2.0    0.0    0.0   -2.0   -2.0   -1.0
98      506669.07    0.0    3.0    2.0    7.0    0.0    7.0
99      292596.07    5.0    5.0    5.0    3.0   -2.0    2.0

[100 rows x 7 columns]

In [5]:
#membagi 2 kolom numerical dan kategorical
df_inf_num = df_inf[['limit_balance']]
df_inf_cat= df_inf[['pay_1', 'pay_2', 'pay_3', 'pay_4','pay_5','pay_6']]

print(df_inf_cat)
print(df_inf_num)

    pay_1  pay_2  pay_3  pay_4  pay_5  pay_6
0     3.0    7.0   -2.0    5.0    4.0    4.0
1     4.0    7.0   -1.0    4.0    5.0    2.0
2     7.0    0.0   -1.0    3.0   -1.0   -1.0
3    -2.0    5.0    7.0   -2.0   -1.0    7.0
4     4.0    6.0    2.0   -1.0    2.0    2.0
..    ...    ...    ...    ...    ...    ...
95    2.0    7.0   -2.0    8.0    7.0   -1.0
96    5.0    1.0    0.0    3.0   -2.0    4.0
97   -2.0    0.0    0.0   -2.0   -2.0   -1.0
98    0.0    3.0    2.0    7.0    0.0    7.0
99    5.0    5.0    5.0    3.0   -2.0    2.0

[100 rows x 6 columns]
    limit_balance
0       589504.01
1       418154.87
2       111006.10
3       719503.58
4       644347.27
..            ...
95      711053.63
96       30414.87
97      765526.27
98      506669.07
99      292596.07

[100 rows x 1 columns]

## Scaling

In [6]:
df_inf_num_scaled = scaler.transform(df_inf_num)
df_inf_num_scaled=pd.DataFrame(df_inf_num_scaled)
df_inf_num_scaled

           0
0   1.159008
1   0.816310
2   0.202012
3   1.419007
4   1.268695
..       ...
95  1.402107
96  0.040830
97  1.511053
98  0.993338
99  0.565192

[100 rows x 1 columns]

## Menggabungkan 2 kolom numerikal yang sudah di scaling dan kolom kategorical

In [7]:
df_inf_final = np.concatenate([df_inf_num_scaled,df_inf_cat],axis = 1)
df_inf_final

array([[ 1.15900802e+00,  3.00000000e+00,  7.00000000e+00,
        -2.00000000e+00,  5.00000000e+00,  4.00000000e+00,
         4.00000000e+00],
       [ 8.16309740e-01,  4.00000000e+00,  7.00000000e+00,
        -1.00000000e+00,  4.00000000e+00,  5.00000000e+00,
         2.00000000e+00],
       [ 2.02012200e-01,  7.00000000e+00,  0.00000000e+00,
        -1.00000000e+00,  3.00000000e+00, -1.00000000e+00,
        -1.00000000e+00],
       [ 1.41900716e+00, -2.00000000e+00,  5.00000000e+00,
         7.00000000e+00, -2.00000000e+00, -1.00000000e+00,
         7.00000000e+00],
       [ 1.26869454e+00,  4.00000000e+00,  6.00000000e+00,
         2.00000000e+00, -1.00000000e+00,  2.00000000e+00,
         2.00000000e+00],
       [ 1.31670836e+00,  0.00000000e+00,  4.00000000e+00,
        -2.00000000e+00,  2.00000000e+00, -2.00000000e+00,
         2.00000000e+00],
       [ 1.30019382e+00,  1.00000000e+00,  0.00000000e+00,
         5.00000000e+00, -2.00000000e+00, -1.00000000e+00,
        -1.00000000e+00],
       [ 1.17729978e+00, -2.00000000e+00,  3.00000000e+00,
         7.00000000e+00,  5.00000000e+00,  6.00000000e+00,
        -1.00000000e+00],
       [ 1.26058024e+00, -1.00000000e+00,  4.00000000e+00,
         5.00000000e+00,  8.00000000e+00, -2.00000000e+00,
         2.00000000e+00],
       [ 7.90263720e-01,  5.00000000e+00,  6.00000000e+00,
         4.00000000e+00,  3.00000000e+00,  6.00000000e+00,
        -2.00000000e+00],
       [ 1.57472488e+00,  3.00000000e+00,  0.00000000e+00,
         4.00000000e+00,  6.00000000e+00,  3.00000000e+00,
         6.00000000e+00],
       [ 8.65656780e-01,  2.00000000e+00,  7.00000000e+00,
         3.00000000e+00,  7.00000000e+00,  2.00000000e+00,
         4.00000000e+00],
       [ 1.67719280e-01, -1.00000000e+00,  7.00000000e+00,
         7.00000000e+00,  4.00000000e+00, -2.00000000e+00,
         7.00000000e+00],
       [ 1.04256420e-01, -1.00000000e+00,  4.00000000e+00,
         6.00000000e+00,  3.00000000e+00, -2.00000000e+00,
         0.00000000e+00],
       [ 6.46436820e-01,  3.00000000e+00, -1.00000000e+00,
         4.00000000e+00, -2.00000000e+00, -2.00000000e+00,
         4.00000000e+00],
       [ 6.75924020e-01,  4.00000000e+00, -2.00000000e+00,
         7.00000000e+00,  0.00000000e+00,  2.00000000e+00,
         0.00000000e+00],
       [ 1.52269298e+00,  7.00000000e+00,  0.00000000e+00,
         6.00000000e+00, -1.00000000e+00, -1.00000000e+00,
         3.00000000e+00],
       [ 1.42431576e+00,  6.00000000e+00,  5.00000000e+00,
         2.00000000e+00,  0.00000000e+00,  3.00000000e+00,
         0.00000000e+00],
       [ 1.43775238e+00,  6.00000000e+00,  0.00000000e+00,
         2.00000000e+00,  7.00000000e+00,  6.00000000e+00,
         4.00000000e+00],
       [ 7.90671500e-01,  6.00000000e+00,  1.00000000e+00,
         2.00000000e+00, -2.00000000e+00,  4.00000000e+00,
        -1.00000000e+00],
       [ 1.54725014e+00,  3.00000000e+00,  7.00000000e+00,
        -2.00000000e+00,  7.00000000e+00, -1.00000000e+00,
         2.00000000e+00],
       [ 2.45447000e-02,  3.00000000e+00, -2.00000000e+00,
        -1.00000000e+00,  3.00000000e+00, -2.00000000e+00,
         4.00000000e+00],
       [ 1.31674484e+00,  0.00000000e+00,  5.00000000e+00,
         4.00000000e+00,  5.00000000e+00,  0.00000000e+00,
        -2.00000000e+00],
       [ 7.08348780e-01,  2.00000000e+00,  3.00000000e+00,
         5.00000000e+00,  5.00000000e+00,  7.00000000e+00,
        -2.00000000e+00],
       [ 6.70217720e-01,  8.00000000e+00,  6.00000000e+00,
         6.00000000e+00, -1.00000000e+00, -1.00000000e+00,
         7.00000000e+00],
       [ 7.48825800e-01,  3.00000000e+00, -1.00000000e+00,
         7.00000000e+00,  5.00000000e+00,  3.00000000e+00,
         2.00000000e+00],
       [ 3.95449760e-01,  4.00000000e+00,  5.00000000e+00,
         7.00000000e+00,  8.00000000e+00,  7.00000000e+00,
        -2.00000000e+00],
       [ 1.52949190e+00,  8.00000000e+00,  5.00000000e+00,
         0.00000000e+00,  7.00000000e+00,  4.00000000e+00,
         4.00000000e+00],
       [ 4.16951820e-01,  3.00000000e+00,  1.00000000e+00,
         4.00000000e+00,  2.00000000e+00, -2.00000000e+00,
         0.00000000e+00],
       [ 1.56280826e+00,  7.00000000e+00,  3.00000000e+00,
        -1.00000000e+00,  4.00000000e+00,  3.00000000e+00,
         3.00000000e+00],
       [ 3.88038600e-01,  4.00000000e+00,  5.00000000e+00,
         3.00000000e+00,  2.00000000e+00,  3.00000000e+00,
        -1.00000000e+00],
       [ 4.48408060e-01, -1.00000000e+00,  0.00000000e+00,
         4.00000000e+00, -2.00000000e+00, -1.00000000e+00,
         0.00000000e+00],
       [ 1.05686012e+00,  0.00000000e+00,  7.00000000e+00,
         7.00000000e+00,  4.00000000e+00,  2.00000000e+00,
        -1.00000000e+00],
       [ 1.51316330e+00,  0.00000000e+00, -2.00000000e+00,
         3.00000000e+00,  0.00000000e+00, -2.00000000e+00,
         0.00000000e+00],
       [ 4.21319480e-01,  6.00000000e+00, -2.00000000e+00,
         5.00000000e+00,  8.00000000e+00,  0.00000000e+00,
         7.00000000e+00],
       [ 1.26462398e+00,  7.00000000e+00, -1.00000000e+00,
         0.00000000e+00, -1.00000000e+00,  6.00000000e+00,
         3.00000000e+00],
       [ 1.21720940e+00,  0.00000000e+00,  1.00000000e+00,
         6.00000000e+00, -1.00000000e+00,  3.00000000e+00,
         7.00000000e+00],
       [ 4.33205380e-01,  8.00000000e+00,  2.00000000e+00,
         6.00000000e+00, -1.00000000e+00,  0.00000000e+00,
         7.00000000e+00],
       [ 1.53240570e+00,  5.00000000e+00,  5.00000000e+00,
         6.00000000e+00,  0.00000000e+00, -1.00000000e+00,
        -2.00000000e+00],
       [ 1.04215520e-01, -1.00000000e+00,  0.00000000e+00,
         7.00000000e+00, -1.00000000e+00,  7.00000000e+00,
         2.00000000e+00],
       [ 6.58993880e-01, -2.00000000e+00,  4.00000000e+00,
        -1.00000000e+00, -1.00000000e+00, -2.00000000e+00,
         2.00000000e+00],
       [ 6.22574600e-01,  5.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  5.00000000e+00, -2.00000000e+00,
         0.00000000e+00],
       [ 2.19483460e-01, -1.00000000e+00,  3.00000000e+00,
         5.00000000e+00,  4.00000000e+00, -2.00000000e+00,
         4.00000000e+00],
       [ 1.18478002e+00,  5.00000000e+00,  3.00000000e+00,
        -2.00000000e+00,  0.00000000e+00,  4.00000000e+00,
         0.00000000e+00],
       [ 4.35200780e-01, -1.00000000e+00,  2.00000000e+00,
         4.00000000e+00,  3.00000000e+00,  7.00000000e+00,
         3.00000000e+00],
       [ 2.53880300e-01,  2.00000000e+00,  4.00000000e+00,
         7.00000000e+00,  0.00000000e+00,  5.00000000e+00,
        -2.00000000e+00],
       [ 1.38949008e+00, -1.00000000e+00,  7.00000000e+00,
        -2.00000000e+00,  7.00000000e+00,  5.00000000e+00,
         6.00000000e+00],
       [ 1.17224286e+00,  5.00000000e+00, -1.00000000e+00,
         5.00000000e+00,  0.00000000e+00,  4.00000000e+00,
        -2.00000000e+00],
       [ 1.79306000e-03,  2.00000000e+00,  1.00000000e+00,
        -1.00000000e+00,  2.00000000e+00,  6.00000000e+00,
         3.00000000e+00],
       [ 1.27048136e+00,  1.00000000e+00,  1.00000000e+00,
         7.00000000e+00,  0.00000000e+00,  4.00000000e+00,
         2.00000000e+00],
       [ 2.20517060e-01,  8.00000000e+00,  4.00000000e+00,
        -1.00000000e+00,  7.00000000e+00,  0.00000000e+00,
         6.00000000e+00],
       [ 7.96931180e-01,  0.00000000e+00,  2.00000000e+00,
         5.00000000e+00, -1.00000000e+00,  4.00000000e+00,
         6.00000000e+00],
       [ 6.38050700e-01,  4.00000000e+00,  2.00000000e+00,
         5.00000000e+00,  0.00000000e+00,  2.00000000e+00,
         7.00000000e+00],
       [ 8.88777200e-02,  5.00000000e+00,  3.00000000e+00,
         2.00000000e+00, -1.00000000e+00,  3.00000000e+00,
         3.00000000e+00],
       [ 2.80981280e-01,  8.00000000e+00,  3.00000000e+00,
         4.00000000e+00,  3.00000000e+00,  7.00000000e+00,
         6.00000000e+00],
       [ 8.38441720e-01,  5.00000000e+00,  2.00000000e+00,
        -1.00000000e+00,  6.00000000e+00, -1.00000000e+00,
         4.00000000e+00],
       [ 8.83077000e-01,  3.00000000e+00,  6.00000000e+00,
        -1.00000000e+00,  6.00000000e+00,  7.00000000e+00,
        -2.00000000e+00],
       [ 1.37768076e+00,  1.00000000e+00,  2.00000000e+00,
        -2.00000000e+00,  4.00000000e+00,  2.00000000e+00,
         0.00000000e+00],
       [ 4.69508700e-01,  0.00000000e+00,  6.00000000e+00,
         7.00000000e+00,  4.00000000e+00,  0.00000000e+00,
         6.00000000e+00],
       [ 1.55554380e-01, -1.00000000e+00,  1.00000000e+00,
         5.00000000e+00,  0.00000000e+00,  5.00000000e+00,
         7.00000000e+00],
       [ 8.28134640e-01, -1.00000000e+00,  7.00000000e+00,
        -2.00000000e+00, -1.00000000e+00,  7.00000000e+00,
        -1.00000000e+00],
       [ 4.60855180e-01,  7.00000000e+00,  7.00000000e+00,
         0.00000000e+00,  4.00000000e+00,  3.00000000e+00,
         7.00000000e+00],
       [ 1.37799896e+00,  1.00000000e+00, -1.00000000e+00,
         5.00000000e+00,  2.00000000e+00, -2.00000000e+00,
        -2.00000000e+00],
       [ 5.69457760e-01,  5.00000000e+00, -2.00000000e+00,
         5.00000000e+00,  7.00000000e+00, -2.00000000e+00,
         6.00000000e+00],
       [ 1.05440684e+00,  5.00000000e+00,  3.00000000e+00,
         6.00000000e+00,  7.00000000e+00,  7.00000000e+00,
         2.00000000e+00],
       [ 1.54523474e+00,  8.00000000e+00,  0.00000000e+00,
        -1.00000000e+00,  8.00000000e+00,  7.00000000e+00,
        -1.00000000e+00],
       [ 9.67826200e-01, -2.00000000e+00,  1.00000000e+00,
        -1.00000000e+00,  2.00000000e+00,  0.00000000e+00,
         3.00000000e+00],
       [ 5.07972220e-01,  5.00000000e+00,  7.00000000e+00,
        -2.00000000e+00,  6.00000000e+00,  7.00000000e+00,
         2.00000000e+00],
       [ 1.54995336e+00,  6.00000000e+00,  3.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  5.00000000e+00,
         4.00000000e+00],
       [ 1.31358794e+00,  1.00000000e+00, -2.00000000e+00,
         4.00000000e+00, -1.00000000e+00, -2.00000000e+00,
         2.00000000e+00],
       [ 1.28466958e+00,  7.00000000e+00,  0.00000000e+00,
         2.00000000e+00,  8.00000000e+00,  4.00000000e+00,
         0.00000000e+00],
       [ 1.28917768e+00, -1.00000000e+00,  5.00000000e+00,
        -1.00000000e+00,  7.00000000e+00,  4.00000000e+00,
         0.00000000e+00],
       [ 5.13942000e-01,  5.00000000e+00,  6.00000000e+00,
         6.00000000e+00,  4.00000000e+00, -2.00000000e+00,
         6.00000000e+00],
       [ 1.41851518e+00,  4.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  0.00000000e+00,  4.00000000e+00,
         3.00000000e+00],
       [ 1.16731460e-01,  2.00000000e+00,  0.00000000e+00,
         2.00000000e+00,  3.00000000e+00, -2.00000000e+00,
         6.00000000e+00],
       [ 7.49709100e-01,  8.00000000e+00,  6.00000000e+00,
         0.00000000e+00,  4.00000000e+00,  0.00000000e+00,
         3.00000000e+00],
       [ 1.46977178e+00, -1.00000000e+00,  6.00000000e+00,
         2.00000000e+00,  4.00000000e+00,  2.00000000e+00,
         7.00000000e+00],
       [ 4.46727080e-01,  4.00000000e+00,  2.00000000e+00,
         6.00000000e+00, -1.00000000e+00, -2.00000000e+00,
        -2.00000000e+00],
       [ 7.20480460e-01,  8.00000000e+00,  2.00000000e+00,
         2.00000000e+00,  3.00000000e+00,  4.00000000e+00,
         6.00000000e+00],
       [ 1.22230536e+00,  8.00000000e+00,  0.00000000e+00,
         6.00000000e+00,  6.00000000e+00,  0.00000000e+00,
        -1.00000000e+00],
       [ 1.24906216e+00,  4.00000000e+00,  0.00000000e+00,
         4.00000000e+00,  4.00000000e+00,  2.00000000e+00,
         7.00000000e+00],
       [ 6.14352300e-01,  3.00000000e+00,  1.00000000e+00,
         3.00000000e+00,  5.00000000e+00,  5.00000000e+00,
        -1.00000000e+00],
       [ 9.66693380e-01,  2.00000000e+00,  0.00000000e+00,
         2.00000000e+00, -1.00000000e+00,  6.00000000e+00,
         0.00000000e+00],
       [ 3.27011000e-01,  1.00000000e+00,  3.00000000e+00,
        -2.00000000e+00,  4.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 1.21537480e-01,  8.00000000e+00, -2.00000000e+00,
         6.00000000e+00,  3.00000000e+00,  2.00000000e+00,
         7.00000000e+00],
       [ 1.48144458e+00,  2.00000000e+00,  5.00000000e+00,
         2.00000000e+00,  6.00000000e+00,  4.00000000e+00,
        -2.00000000e+00],
       [ 5.53258240e-01,  3.00000000e+00,  4.00000000e+00,
         6.00000000e+00,  7.00000000e+00,  0.00000000e+00,
         4.00000000e+00],
       [ 1.42827160e+00, -2.00000000e+00, -1.00000000e+00,
         6.00000000e+00, -1.00000000e+00,  6.00000000e+00,
        -2.00000000e+00],
       [ 1.12536492e+00,  5.00000000e+00,  3.00000000e+00,
        -1.00000000e+00,  6.00000000e+00,  4.00000000e+00,
        -2.00000000e+00],
       [ 3.76271600e-01, -2.00000000e+00, -2.00000000e+00,
         7.00000000e+00,  0.00000000e+00,  4.00000000e+00,
        -2.00000000e+00],
       [ 1.46128430e+00,  6.00000000e+00,  3.00000000e+00,
         3.00000000e+00,  3.00000000e+00, -1.00000000e+00,
         3.00000000e+00],
       [ 1.13234580e-01,  7.00000000e+00,  4.00000000e+00,
         3.00000000e+00,  5.00000000e+00, -1.00000000e+00,
         7.00000000e+00],
       [ 4.48043340e-01,  1.00000000e+00, -1.00000000e+00,
        -2.00000000e+00,  2.00000000e+00,  7.00000000e+00,
         0.00000000e+00],
       [ 6.65417000e-01,  5.00000000e+00, -1.00000000e+00,
         6.00000000e+00,  8.00000000e+00, -1.00000000e+00,
        -1.00000000e+00],
       [ 2.25847160e-01,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  4.00000000e+00,  6.00000000e+00,
         6.00000000e+00],
       [ 1.40210726e+00,  2.00000000e+00,  7.00000000e+00,
        -2.00000000e+00,  8.00000000e+00,  7.00000000e+00,
        -1.00000000e+00],
       [ 4.08297400e-02,  5.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  3.00000000e+00, -2.00000000e+00,
         4.00000000e+00],
       [ 1.51105254e+00, -2.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -2.00000000e+00, -2.00000000e+00,
        -1.00000000e+00],
       [ 9.93338140e-01,  0.00000000e+00,  3.00000000e+00,
         2.00000000e+00,  7.00000000e+00,  0.00000000e+00,
         7.00000000e+00],
       [ 5.65192140e-01,  5.00000000e+00,  5.00000000e+00,
         5.00000000e+00,  3.00000000e+00, -2.00000000e+00,
         2.00000000e+00]])

In [8]:
#membuat kolom predict 
y_pred_inf = model_knn.predict(df_inf_final)
y_pred_inf

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [9]:
#membuat kolom predict kedalam data frame dan memberi nama kolomnya dengan 'Def_payment - Prediction'
y_pred_inf_df = pd.DataFrame(y_pred_inf, columns=['Def_payment - Prediction'])
y_pred_inf_df

    Def_payment - Prediction
0                          1
1                          1
2                          1
3                          0
4                          1
..                       ...
95                         1
96                         1
97                         0
98                         1
99                         0

[100 rows x 1 columns]

In [10]:
#membuat variabel baru dengan menggabungkan 2 tabel yaitu df_inf dan y _preditc inf
tabel_inference = pd.concat([df_inf, y_pred_inf_df], axis=1)
tabel_inference

,limit_balance,pay_1,pay_2,pay_3,pay_4,pay_5,pay_6,Def_payment - Prediction
0,589504.01,3.0,7.0,-2.0,5.0,4.0,4.0,1
1,418154.87,4.0,7.0,-1.0,4.0,5.0,2.0,1
2,111006.10,7.0,0.0,-1.0,3.0,-1.0,-1.0,1
3,719503.58,-2.0,5.0,7.0,-2.0,-1.0,7.0,0
4,644347.27,4.0,6.0,2.0,-1.0,2.0,2.0,1
...,...,...,...,...,...,...,...,...
95,711053.63,2.0,7.0,-2.0,8.0,7.0,-1.0,1
96,30414.87,5.0,1.0,0.0,3.0,-2.0,4.0,1
97,765526.27,-2.0,0.0,0.0,-2.0,-2.0,-1.0,0
98,506669.07,0.0,3.0,2.0,7.0,0.0,7.0,1
99,292596.07,5.0,5.0,5.0,3.0,-2.0,2.0,0

# xii. Kesimpulan

- I chose f1 score as the score parameter because I think minimizing false positives and false negatives is important.

- From the STD results which are close to 0 and below the mean, it means that the KNN model has a default STD value of 0.03 so the model is the best fit. So it can be said that the default knn model has good consistency, but the validation of the prediction results is not good because it is only around 48%. From a business perspective, this model cannot be used because the prediction results are still less than 50% good, so it can lead to wrong prediction results which can cause the company to suffer losses. In the future, it is possible to increase feature selection, increase parameter selection to improve model performance and even try new models so that you can choose more of the best models.

- To increase the number of users who can pay, it's a good idea to bill on payday around 25-31 during payday because on that date they have a lot of money so they can pay

- The majority of users come from graduate and university backgrounds. Maybe in the future a threshold can be selected or given for users who can use this facility because users with high school level education, others, and unknowns may not have income or their income is small so it is more likely that they will fail to pay. When we set a threshold for users with a large or fixed income, we can reduce the percentage of defaults

- The KNN model cannot be used to solve problem statements because the F1 score accuracy rate is only 46% so it cannot be used to reduce the level of non-payment on default payments.